"""
Django settings for testcurd project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import firebase_admin
from firebase_admin import credentials

SESSION_COOKIE_SECURE = True  # Ensure cookies are only sent over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookies
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire sessions when the browser is closed
SESSION_COOKIE_AGE = 1800  # Set session to expire after 30 minutes (1800 seconds)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

cred_path = os.path.join(BASE_DIR, 'config', 'plant-10a6f-firebase-adminsdk-nzoej-fa3706ab78.json')
cred = credentials.Certificate(cred_path)
firebase_admin.initialize_app(cred)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vt8z9=akmxf0dpo)nvgll+n!^4@))iq3uz0s(1nx4a&#g&$@+a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
"""
ALLOWED_HOSTS = [
    'vikas04488.pythonanywhere.com',
    'https://vikas04488.pythonanywhere.com',# Replace with your actual domain
    'http://vikas04488.pythonanywhere.com',
    'https://www.vikas04488.pythonanywhere.com',
    'http://www.vikas04488.pythonanywhere.com',
    'localhost',
    '127.0.0.1',
]
"""
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bubble',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'testcurd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bubble.context_processors.allcatagories',
                'bubble.context_processors.getcartCount',
                'bubble.context_processors.getlikeCount',
            ],
        },
    },
]

WSGI_APPLICATION = 'testcurd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'vikas04488$plantdb',
        'USER':'vikas04488',
        'PASSWORD':'tango@04488',
        'HOST':'vikas04488.mysql.pythonanywhere-services.com',
        'PORT':'3306',
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'railway',
        'USER': 'root',
        'PASSWORD': 'DCDAsHzXVVAfHBanQvBuGvCLcbJPCDvO',
        'HOST': 'mysql.railway.internal',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, '/static')] 
STATICFILES_DIRS = '/plantstorage/static'
#STATIC_ROOT = os.path.join(BASE_DIR, '/staticfiles')
STATIC_ROOT = '/plantstorage/staticfiles'
MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, '/media/')
MEDIA_ROOT = '/plantstorage/media/'

#STATIC_URL = 'static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
#STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

#MEDIA_ROOT = '/home/vikas04488/plant/bubble/static/media'
#MEDIA_URL = '/media/'
#STATIC_ROOT = '/home/vikas04488/plant/bubble/static'
#STATIC_URL = '/static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'vikas04488@gmail.com'
EMAIL_HOST_PASSWORD = '********'
EMAIL_PORT = 587

LOGIN_URL='/flowerhome'
LOGIN_REDIRECT_URL='/path/to/redirecturl'
PHONEPE_MID = 'PGTESTPAYUAT77'
PHONEPE_SALT_INDEX = '1'
PHONEPE_SALT_KEY = '14fa5465-f8a7-443f-8477-f986b8fcfde9'
PHONEPE_BASE_URL = 'https://api-preprod.phonepe.com/apis/pg-sandbox'
PHONEPE_REDIRECT_URL = 'https://railway-production-0aed.up.railway.app/callback'
CSRF_TRUSTED_ORIGINS = ['https://*.railway.app']
handler404 = 'bubble.views.custom_404'

