# Generated by Django 5.0.4 on 2024-05-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='subcat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bubble.subcategory'),
        ),
    ]
