# Generated by Django 5.0.4 on 2024-06-28 02:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0002_alter_flowers_subcat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=400)),
                ('orderDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.FloatField()),
                ('offvalue', models.FloatField()),
                ('flowerob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubble.flowers')),
                ('userob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aa_myorder',
            },
        ),
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transectiondate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('statusCode', models.CharField(max_length=400)),
                ('transactionId', models.CharField(max_length=400)),
                ('providerReferenceId', models.CharField(max_length=400)),
                ('amount', models.FloatField()),
                ('userob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aa_transection',
            },
        ),
    ]
