# Generated by Django 4.0.6 on 2024-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0003_myorders_transection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='offvalue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='offvalue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transection',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
